"use client";

import {
  IconPlayerPlayFilled,
  IconPlayerStopFilled,
} from "@tabler/icons-react";
import { useRef, useState } from "react";
import IconButton from "./icon-button";

export default function AudioPlayer({ src }: { src: string }) {
  const [isPlaying, setIsPlaying] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const togglePlay = () => {
    if (isPlaying) audioRef.current?.pause();
    else audioRef.current?.play();
    setIsPlaying(!isPlaying);
  };

  return (
    <div className="flex items-center gap-3 min-w-50">
      <audio
        ref={audioRef}
        src={src}
        onEnded={() => setIsPlaying(false)}
        className="hidden"
      />
      <IconButton onClick={togglePlay} className="size-8  text-white">
        {isPlaying ? <IconPlayerStopFilled /> : <IconPlayerPlayFilled />}
      </IconButton>
      <svg
        width="190"
        height="32"
        viewBox="0 0 190 32"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          opacity="0.66"
          y="15"
          width="2"
          height="2"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="6"
          y="12"
          width="2"
          height="8"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="12"
          y="9"
          width="2"
          height="14"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="18"
          y="14"
          width="2"
          height="4"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="24"
          y="2"
          width="2"
          height="28"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="132"
          y="14"
          width="2"
          height="4"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="138"
          y="2"
          width="2"
          height="28"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="144"
          y="5"
          width="2"
          height="22"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="150"
          y="9"
          width="2"
          height="14"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="30"
          y="9"
          width="2"
          height="14"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="36"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="42"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="48"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="54"
          y="6"
          width="2"
          height="20"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="60"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="66"
          y="8"
          width="2"
          height="16"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="72"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="156"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="162"
          y="8"
          width="2"
          height="16"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="168"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="186"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="90"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="96"
          y="6"
          width="2"
          height="20"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="78"
          y="14"
          width="2"
          height="4"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="84"
          y="15"
          width="2"
          height="2"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="102"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="108"
          y="8"
          width="2"
          height="16"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="114"
          y="11"
          width="2"
          height="10"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="174"
          y="14"
          width="2"
          height="4"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="180"
          y="15"
          width="2"
          height="2"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="120"
          y="14"
          width="2"
          height="4"
          rx="1"
          fill="#F1F1F1"
        />
        <rect
          opacity="0.66"
          x="126"
          y="15"
          width="2"
          height="2"
          rx="1"
          fill="#F1F1F1"
        />
      </svg>
    </div>
  );
}
